version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4
      - image: postgres:9.5.1
        environment:
          POSTGRES_USER: root

    working_directory: ~/shikimori
    steps:
      - checkout
      - type: shell
        name: Install System Dependencies
        command: apt-get update -qq && apt-get install -y build-essential libmysqlclient-dev nodejs
      - type: cache-restore
        key: gemfile-{{ checksum "Gemfile.lock" }}
      - type: shell
        name: Install Ruby Dependencies
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - type: cache-save
        key: gemfile-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - type: shell
        name: Create DB
        command: bundle exec rake db:create db:schema:load --trace
      - type: shell
        name: Run specs
        command: bundle exec rspec spec
