'Охотник х Охотник [ТВ-1]': 136
'Охотник х Охотник [ТВ -2]': 11061
'Megami Kouhosei OVA': 887
'Lupin the Third Episode 0 First Contact': 1418
'Evangelion 2.22 You Can [Not] Advance': 3784
'Девы Розена [ТВ 3]': 18041
'Мэйджор [ТВ-1]': 627
