mangas:
  no_matches_yet: true

animes:
  'Охотник х Охотник [ТВ-1]': 136
  'Охотник х Охотник [ТВ -2]': 11061
  'Megami Kouhosei OVA': 887
  'Lupin the Third Episode 0 First Contact': 1418
  'Evangelion 2.22 You Can [Not] Advance': 3784
  'Девы Розена [ТВ 3]': 18041
  'Мэйджор [ТВ-1]': 627
  'Candy Candy [Movie]': 723
  'Digimon Adventure 02 Hurricane Touchdown!': 2962
  'Negima!? Summer OVA-2': 1732
  'Ore no Imouto OVA - True End': 18857
  'Fairy Tail Ecchi OVA': 9982
  'Doki Doki! PreСure': 16419
  'Kateikyoushi Hitman Reborn! OVA': 8532
  'Gekijouban Munto Tenjoubito to Akutobito Saigo no Tatakai': 6169
  'Wrath of the Ninja OVA': 3600
  'DNA2: Dokoka de Nakushita Aitsu no Aitsu OVA': 1187
  'Сакура: Война миров OVA-2': 1166
  'Whimsical Orange Road': 1087
  'Clamp In Wonderland 1 & 2': 2768
  'Seikai no Dansho - Tanjyou OVA': 1124
  'Katekyo Hitman Reborn! The Complete Memory': 8532
  'Мелочи жизни OVA': 8857
  'Nodame Cantabile Puri Gorota': 5656
  'Магический учитель Нэгима! Еще один мир': 6050
  'Kurokami The Animation OVA: Tora to Tsubasa Gaiden': 6587
  'Забить на последней секунде TB-1': 406
  'Naruto Ova 3D Cross Roads': 7367
  'Manga Shouwa Monogatari': 10014
  'Black Rock Shooter[TV]': 11285
#'Aoyama Gosho Short Story Collection OVA 1': 5578
  'Psychic Academy Aura Bansho ONA': 337
  'Manami to Nami Sprite': 1786
  'Recorder to Randsell OVA': 14627
  'Naruto OVA 3': 1074
  'Detective Conan Magic File 2011 the Niigata-Tokyo souvenir capriccio': 10531
  'Towa no Quon Vol. 6 Final': 10717
  'Blue Submarine #6': 1051
  'Garasu no Kamen [TV-2]': 1974
  'Chuunibyou demo Koi ga Shitai! OVA': 16934
  'One Piece Movie II — Clockwork Island Adventure': 460
  'In a Distant Time 2: Priestess of the White Dragon': 1904
  'Kuroko no Basuke FanDisc': 17259
  'Tenchi Muyo! Galaxy Police Transporter': 1133
  'Kidou Senshi Mobile Suit Gundam Unicorn OVA': 6336
  "Aquarian Age Saga II: Don't forget me...": 1268
  'Gokujou. Gokurakuin Joshikou Ryou Monogatari': 11769
  'Choujikuu Seiki': 2089
  'Toriko SP 2009': 6941
  'Ao no Exorcist OVA ~Kuro no Iede~': 11266
  'TO Elliptical Orbit & Symbiotic Planet': 7279
  'Magical Project S [TV]': 1502
  'Kyoshoku Soku Guyver': 6016
  'Kujibiki Unbalance TV': 1591
  'UFO Princess Valkyrie/ Enban Oujo Valkyrie': 1127
  'Kyo Kara Maoh! R': 2971
  'Monkey Punch': 5343
  'H.P. Lovecraft no Dunwich Horror': 3906
  'Ring ni Kakero': 23
  'Urusei Yatsura OVA Series': 1919
  'Honoo no Chuunin Shiken! Naruto vs Konohamaru!': 10686
  'Yuru Yuri 2': 12403
  'Dyurarara!!': 6746
  'Девочка-волшебница Мадока (компиляция)': 11977
  'Major [ТВ-1]': 627
  'Граница пустоты: Сад грешников (фильм первый)': 2593
  'Хроника Крыльев (сезон первый)': 177
  'School Days OVA-2: Magical Heart Kokoro-chan': 3328
  'Gekijouban Kara no Kyoukai: Dai Nana Shou - Satsujin Kousatsu (Go)': 5205
  'Команда ученых - ниндзя Гатчамен': 3154
  'Дораэмон-1979': 2471
  'Детектив Конан (фильм 08)': 1367
  'Inuyasha Movie 1': 452
  'Wish upon a Star': 7230
  "Tales of Symphonia: Tethe'alla Chapter": 5306
  'Konan tai Kid tai Yaiba: Houtou Soudatsu Daikessen!!': 1369
  'Akahori Gedou Hour Rabuge': 309
  'DiGi Charat Summer Special': 1754
  'UFO Princess Walküre: Seiresetsu no Hanayome': 1514
  'Digimon Zero Two': 1313
  'Eiga Futari wa Precure Max Heart! The God is a frog. Movie 1': 1930
  'Ayu Mayu Theater OVA': 1856
  'Pokemon the Movie 9: Umino Ouji - Manafi': 2201
  'Pocket Monsters Advanced': 1526
  'Air - Theatrical Feature': 713
  'Hakkenden: Eight Dogs of the East [TV-2]': 18055
  'Toriko TV-1': 10033
  'Gekijouban Hunter x Hunter: Phantom Rouge': 13271
  'Kami nomi zo Shiru Sekai: Magical Star Kanon 100%': 17725
  'Saint Seiya Omega: New Cloth Hen': 12929
  'Rinne no Lagrange TV-2': 12281
  'Gall Force: Eternal Story': 2060
  'Rinne no Lagrange TV-1': 11227
  'Magic Teacher Negima! Spring, OVA-1': 1619
  'Poltergeist Report: Fight': 2125
  'Project ARMS TV-1': 1492
  'Project Arms TV-2': 1493
  'Loups-Garous': 7598
  'Superbook season 2': 3936
  'One Piece: The Detective Memoirs of Boss Straw Hat Luffy': 2020
  'One Piece: Protect! The Last Great Stage': 1238
  "One Piece: Open Upon the Great Sea! A Father's Huge, HUGE Dream!": 1237
  'Hell Teacher Nube 1997': 8228
  'Kidou Senshi Gundam 0083 - Zeon no Zankou': 2695
  'Detective Conan: Count Down to Heaven': 1364
  'Detective Conan: Captured In Her Eyes': 1363
  "Detective Conan: High School Girl Detective Sonoko Suzuki's Case File": 6198
  'Detective Conan: The Timed Skyscraper': 779
  'Meitantei Conan: 10 Nengo no Strange': 6438
  'Белый Альбом (второй сезон)': 6165
  'Белый альбом 2 (2013)': 18245
  'Seitokai Yakuindomo: Kaette Kita Seitokai': 10119
  'Fairy Tail: The Maiden of the Phoenix': 12049
  'Naruto Shippuden: The Will of Fire Still Burns': 6325
  'Ayakashi - Samurai Horror Tales': 586
  'Hunter x Hunter [TV-2]': 11061
  'Hunter X Hunter - G I Final': 139
  'Nodame Cantabile: Paris Chapter': 4477
  'Code Geass: Lelouch of the Rebellion R2': 2904
  'Inuyasha: The Final Act': 6811
  'Infinite Stratos Encore: Koi ni Kogareru Rokujuso': 10794
  'Gekijo-ban Tennis no Ouji-sama Eikoku Shikiteikyu-jo Kessen!': 10731
  'Gekijouban Pocket Monsters: Best Wishes - Kyurem vs Seikenshi Keldeo': 12671
  "You're Under Arrest The Motion Picture": 2013
  'Chie the Brat': 3947
  'Shin Kyuseishu Densetsu Hokuto no Ken Zero: Kenshiro-den': 5291
  'One Piece: The Desert Princess and The Pirates: Adventure in Alabasta': 2107
  'One Piece: The Movie': 459
  'Seitokai Yakuindomo - Kaette Kita Seitokai Yakuindomo': 10119
  'Gintama (2013)': 15335
  'Gekijouban Gintama: Shinyaku Benizakura Hen': 7472
  'Gintama [TV-2]': 9969
  'Yuru Yuri': 10495
  'Strike Witches 2-ki': 6381
  'Darker than BLACK - Ryuusei no Gemini OVA': 7338
  'JoJo no Kimyou na Bouken [OVA-2]': 665
  'Fushigi Yuugi OVA 1': 380
  'Gargantia on the Verdurous Planet Sp': 18413
  'Mermaid Forest': 2016
  'Black Jack OVA': 1520
  'Black Jack (2004)': 2213
  'Sora no Otoshimono: Project Pink Tougenkyou': 7858
  'Kuroshitsuji II: Spiders Intention': 9136
  'Ore no Imouto ga Konnani Kawaii Wake ga Nai [TV-2]': 13659
  'Shadow Skill TV': 678
  'Meitantei Conan: Kid in Trap Island': 8609
  "Problem Children are Coming from Another World, aren't they? - [OVA]": 16444
  'Buzzer Beater TV-2': 2684
  'Love Live! School Idol Project 2013': 15051
  'Crazy KOUZU Basketball Club': 359
  'Koukaku Kidoutai Arise: Ghost in the Shell': 17187
  'Стеклянная маска OVA': 3734
  'Ai no Kusabi OVA-2': 5784
  'Broken Blade: Fifth Chapter - Horizon Between Life and Death': 9724
  'Broken Blade: Fourth Chapter - Ground of Calamity': 9465
  "Broken Blade: Third Chapter - Mark of the Assassin's Dagger": 9252
  'Broken Blade: The Split Path': 8514
  'Broken Blade: Hour of Awakening': 6772
  'Broken Blade: Sixth Chapter - Enclave of Lamentations': 10092
  'Mobile Suit Gundam SEED: Movie I - The Empty Battlefield': 2269
  'The Secret of Haruka Nogizaka: Purity': 6023
  'All Purpose Cultural Cat Girl Nuku Nuku': 375
  'All Purpose Cultural Cat Girl Nuku Nuku OVA 1': 373
  'Gekijouban Naruto Shippuuden: Kizuna': 4437
  'Naruto the Movie: The Great Clash! The Phantom Ruins in the Depths of the Earth': 936
  'Saint Seiya: The Lost Canvas - Meio Shinwa 2nd Chapter': 9130
  'Zetsuai': 1041
  'To Aru Kagaku no Railgun OVA': 9047
  'Ichigo Mashimaro OVA - 1': 1888
  'Kyousougiga ONA': 15359
  'Birdy the Mighty-2': 5074
  'Berserk Golden Age Arc II: The Battle for Doldrey': 12113
  'Принцесса чудовищ OVA': 9159
  'Victorian Romance Emma: Second Act': 2035
  'Happy Lesson OVA/ HAPPY☆LESSON': 259
  'Eureka Seven Ao: Jungfrau no Hana-tachi': 14875
  'Macross II The Movie Edition: Lovers Again': 1262
  'Горничные Ханаукё OVA': 797
  'Aa! Megami-sama!': 9611
  "Lupin III: Napoleon's Dictionary": 1423
  'Lupin III: Hemingway Papers': 1421
  'Lupin III: Tokyo Crisis': 1437
  'Seisenshi Dunbine': 929
  'Wind: A Breath of Heart': 546
  'Samurai Girl': 1098
  'Mahoromatic: Tadaima Okaeri': 7066
  'Ancient Book of Ys I [1989]': 1276
  'Shin Hokuto no Ken: Raoh-den Gekitou no Shou': 2174
  'Shinkon Gattai Godannar the second sesson': 1104
  'Stratos 4 OVA-1': 422
  'Kyo no Gononi TV': 4903
  'Сегодня в 5-Б классе OVA-2': 6379
  'Космические приключения Кобры OVA': 4646
  'Hidamari Sketch × 365': 3604
  'В джунглях всё было хорошо, пока не пришла Гуу: Финал': 255
  'Area 88': 284
  'Меланхолия Харухи Судзумии [ТВ-2]': 4382
  'Дева Мария смотрит за вами OVA': 1729
  'Ronin Warriors: Legend of the Inferno Armor': 1266
  'flag': 5136
  'Достичь Терры': 2560
  "Queen's Blade OVA-2": 10924
  'Tobira O Akete': 3192
  'To Heart: Heart Fighters': 686
  'Неземная принцесса Валькирия 2 [ТВ]': 1128
  'Yume de Aetara [TV]': 718
