mangas:
  no_matches_yet: true

animes:
  'Охотник х Охотник [ТВ-1]': 136
  'Охотник х Охотник [ТВ -2]': 11061
  'Megami Kouhosei OVA': 887
  'Lupin the Third Episode 0 First Contact': 1418
  'Evangelion 2.22 You Can [Not] Advance': 3784
  'Девы Розена [ТВ 3]': 18041
  'Мэйджор [ТВ-1]': 627
  'Candy Candy [Movie]': 723
  'Digimon Adventure 02 Hurricane Touchdown!': 2962
  'Negima!? Summer OVA-2': 1732
  'Gintama (2013)': 15335
  'Ore no Imouto OVA - True End': 18857
  'Fairy Tail Ecchi OVA': 9982
  'Doki Doki! PreСure': 16419
  'Kateikyoushi Hitman Reborn! OVA': 8532
  'Gekijouban Munto Tenjoubito to Akutobito Saigo no Tatakai': 6169
  'Wrath of the Ninja OVA': 3600
  'DNA2: Dokoka de Nakushita Aitsu no Aitsu OVA': 1187
  'Сакура: Война миров OVA-2': 1166
  'Whimsical Orange Road': 1087
  'Clamp In Wonderland 1 & 2': 2768
  'Seikai no Dansho - Tanjyou OVA': 1124
  'Katekyo Hitman Reborn! The Complete Memory': 8532
  'Мелочи жизни OVA': 8857
  'Nodame Cantabile Puri Gorota': 5656
  'Магический учитель Нэгима! Еще один мир': 6050
  'Kurokami The Animation OVA: Tora to Tsubasa Gaiden': 6587
  'Забить на последней секунде TB-1': 406
  'Naruto Ova 3D Cross Roads': 7367
  'Manga Shouwa Monogatari': 10014
  'Black Rock Shooter[TV]': 11285
#'Aoyama Gosho Short Story Collection OVA 1': 5578
  'Psychic Academy Aura Bansho ONA': 337
  'Manami to Nami Sprite': 1786
  'Recorder to Randsell OVA': 14627
  'Naruto OVA 3': 1074
  'Detective Conan Magic File 2011 the Niigata-Tokyo souvenir capriccio': 10531
  'Towa no Quon Vol. 6 Final': 10717
  'Blue Submarine #6': 1051
  'Garasu no Kamen [TV-2]': 1974
  'Chuunibyou demo Koi ga Shitai! OVA': 16934
  'One Piece Movie II — Clockwork Island Adventure': 460
  'In a Distant Time 2: Priestess of the White Dragon': 1904
  'Kuroko no Basuke FanDisc': 17259
  'Tenchi Muyo! Galaxy Police Transporter': 1133
  'Kidou Senshi Mobile Suit Gundam Unicorn OVA': 6336
  "Aquarian Age Saga II: Don't forget me...": 1268
  'Gokujou. Gokurakuin Joshikou Ryou Monogatari': 11769
  'Choujikuu Seiki': 2089
  'Toriko SP 2009': 6941
  'Ao no Exorcist OVA ~Kuro no Iede~': 11266
  'TO Elliptical Orbit & Symbiotic Planet': 7279
  'Magical Project S [TV]': 1502
  'Kyoshoku Soku Guyver': 6016
  'Kujibiki Unbalance TV': 1591
  'UFO Princess Valkyrie/ Enban Oujo Valkyrie': 1127
  'Kyo Kara Maoh! R': 2971
  'Monkey Punch': 5343
  'H.P. Lovecraft no Dunwich Horror': 3906
  'Ring ni Kakero': 23
  'Urusei Yatsura OVA Series': 1919
  'Honoo no Chuunin Shiken! Naruto vs Konohamaru!': 10686
  'Yuru Yuri 2': 12403
  'Dyurarara!!': 6746
  'Девочка-волшебница Мадока (компиляция)': 11977
  'Major [ТВ-1]': 627
  'Граница пустоты: Сад грешников (фильм первый)': 2593
  'Хроника Крыльев (сезон первый)': 177
  'School Days OVA-2: Magical Heart Kokoro-chan': 3328
  'Gekijouban Kara no Kyoukai: Dai Nana Shou - Satsujin Kousatsu (Go)': 5205
  'Команда ученых - ниндзя Гатчамен': 3154
  'Дораэмон-1979': 2471
  'Детектив Конан (фильм 08)': 1367
  'Inuyasha Movie 1': 452
  'Wish upon a Star': 7230
  "Tales of Symphonia: Tethe'alla Chapter": 5306
  'Konan tai Kid tai Yaiba: Houtou Soudatsu Daikessen!!': 1369
  'Akahori Gedou Hour Rabuge': 309
  'DiGi Charat Summer Special': 1754
  'UFO Princess Walküre: Seiresetsu no Hanayome': 1514
  'Digimon Zero Two': 1313
  'Eiga Futari wa Precure Max Heart! The God is a frog. Movie 1': 1930
  'Ayu Mayu Theater OVA': 1856
  'Pokemon the Movie 9: Umino Ouji - Manafi': 2201
  'Pocket Monsters Advanced': 1526
  'Air - Theatrical Feature': 713
  'Hakkenden: Eight Dogs of the East [TV-2]': 18055
  'Toriko TV-1': 10033
  'Gekijouban Hunter x Hunter: Phantom Rouge': 13271
  'Kami nomi zo Shiru Sekai: Magical Star Kanon 100%': 17725
  'Saint Seiya Omega: New Cloth Hen': 12929
  'Rinne no Lagrange TV-2': 12281
  'Gall Force: Eternal Story': 2060
  'Rinne no Lagrange TV-1': 11227
  'Magic Teacher Negima! Spring, OVA-1': 1619
  'Poltergeist Report: Fight': 2125
  'Project ARMS TV-1': 1492
  'Project Arms TV-2': 1493
  'Loups-Garous': 7598
  'Superbook season 2': 3936
  'One Piece: The Detective Memoirs of Boss Straw Hat Luffy': 2020
  'One Piece: Protect! The Last Great Stage': 1238
  "One Piece: Open Upon the Great Sea! A Father's Huge, HUGE Dream!": 1237
  'Gekijouban Gintama: Shinyaku Benizakura Hen': 7472
  'Hell Teacher Nube 1997': 8228
  'Kidou Senshi Gundam 0083 - Zeon no Zankou': 2695
  'Detective Conan: Count Down to Heaven': 1364
  'Detective Conan: Captured In Her Eyes': 1363
  "Detective Conan: High School Girl Detective Sonoko Suzuki's Case File": 6198
  'Detective Conan: The Timed Skyscraper': 779
  'Meitantei Conan: 10 Nengo no Strange': 6438
  'Белый Альбом (второй сезон)': 6165
  'Белый альбом 2 (2013)': 18245
  'Seitokai Yakuindomo: Kaette Kita Seitokai': 10119
  'Fairy Tail: The Maiden of the Phoenix': 12049
  'Naruto Shippuden: The Will of Fire Still Burns': 6325
  'Ayakashi - Samurai Horror Tales': 586
  'Hunter x Hunter [TV-2]': 11061
  'Hunter X Hunter - G I Final': 139
  'Nodame Cantabile: Paris Chapter': 4477
  'Code Geass: Lelouch of the Rebellion R2': 2904
  'Inuyasha: The Final Act': 6811
