---
:episodes_diff:
  "Gintama°": 252
  "Fairy Tail (2014)": 175
  "kuroko no basuke 3": 50

:matches:
  "Daiya no A ~Second Season~": 30230
  "Ushio to Tora": 29854
  "Arslan Senki": 28249
  "Durarara!! ×2 The Second Arc": 27831
  "Q Transformers: Kaettekita Convoy no Nazo 2": 30851
  "Kyōkai no Rinne": 28423
  "Denpa Kyōshi - He Is an Ultimate Teacher": 29589

:ignores:
  - "PriPara"
