---
:ignores:
  - http://www.animespirit.ru/anime/rsb/movie-russub/3995-mobile-suit-gundam-seed-destiny-special-edition.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/3991-mobile-suit-gundam-seed-destiny-special-edition-i.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/3994-mobile-suit-gundam-seed-destiny-special-edition.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/3993-mobilnyj-voin-gandam-sudba-pokoleniya-film-3.html
  - http://www.animespirit.ru/anime/rs/ova-rus/5915-tyomnyj-dvoreckij-ii-dobro-pozhalovat-v.html
  - http://www.animespirit.ru/anime/rs/ova-rus/5916-tyomnyj-dvoreckij-ii-istoriya-zhneca-po-imeni.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/8352-voennyj-orkestr-ova-3-gunparade-orchestra-ova-3.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/8351-voennyj-orkestr-ova-2-gunparade-orchestra-ova-2.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/8350-voennyj-orkestr-ova-1-gunparade-orchestra-ova-1.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/3989-mobilnyj-voin-gandam-pokolenie-film-2-mobile-suit.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/3990-mobile-suit-gundam-seed-movie-iii-the-rumbling.html
  - http://www.animespirit.ru/anime/rs/ova-rus/8766-zhenskaya-logika-ova-joshiraku-ova.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/4224-zhivaya-lyubov-proekt-shkolnyj-idol-ova-2010-love.html
  - http://www.animespirit.ru/anime/rsb/series-russub/8946-rycari-zodiaka-tv-3-saint-seiya-omega-new-cloth.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9686-tripleksogolik-ova-3-xxxholic-rou-adayume.html
  - http://www.animespirit.ru/anime/oth/6588-life-zhizn-ona.html
  - http://www.animespirit.ru/anime/oth/8056-bozhestvennye-morskie-voiny-momotaro-momotaros.html
  - http://www.animespirit.ru/anime/rs/5012-animiya-programma-o-anime.html
  - http://www.animespirit.ru/anime/rs/movie-rus/7177-poslednij-edinorog-the-last-unicorn.html
  - http://www.animespirit.ru/anime/rs/movie-rus/7665-dazhe-dyavol-mozhet-plakat-4-cut-sceny-devil-may.html
  - http://www.animespirit.ru/anime/rs/movie-rus/8193-surovoe-ispytanie-lishennye-golosa-the-crucible.html
  - http://www.animespirit.ru/anime/rs/movie-rus/9536-robotekxroniki-tenej-robotech-the-shadow.html
  - http://www.animespirit.ru/anime/rs/movie-rus/9709-pod-maskoj-izvrashhenca-hentai-kamen.html
  - http://www.animespirit.ru/anime/rs/ova-rus/5914-kak-sozdavalsya-temnyj-dvoreckij-the-making-of.html
  - http://www.animespirit.ru/anime/rs/ova-rus/6077-chlen-shkolnogo-soveta-ova-seitokai-yakuindomo.html
  - http://www.animespirit.ru/anime/rs/ova-rus/7003-toxo-kalejdoskop-fantazii-touhou-gensou-mangekyou.html
  - http://www.animespirit.ru/anime/rs/ova-rus/7313-mini-vakfu-mini-wakfu.html
  - http://www.animespirit.ru/anime/rs/ova-rus/7378-yeksyella-exaella.html
  - http://www.animespirit.ru/anime/rs/ova-rus/7831-sinij-yekzorcist-ova-ao-no-exorcist-ova.html
  - http://www.animespirit.ru/anime/rs/ova-rus/8112-nashestvie-devochki-kalmarki-ova-shinryaku-ika.html
  - http://www.animespirit.ru/anime/rs/ova-rus/8578-dofus-sokrovishha-keruba-dofus-aux-tr233sors-de.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9653-maken-ki-two-takeru-nyotaika-minami-no-shima-de.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9721-hengen-taima-yakou-karura-mau-sendai-kokeshi-onka.html
  - http://www.animespirit.ru/anime/rs/series-rus/4731-vampire-knight-rycar-vampir.html
  - http://www.animespirit.ru/anime/rs/series-rus/6770-vakfu-wakfu-tb.html
  - http://www.animespirit.ru/anime/rs/series-rus/7144-vakfu-tv-2-wakfu-tb-2.html
  - http://www.animespirit.ru/anime/rs/series-rus/7281-avatar-legenda-o-korre-the-last-airbender-the.html
  - http://www.animespirit.ru/anime/rs/series-rus/8317-gromovye-koty-thundercats.html
  - http://www.animespirit.ru/anime/rs/series-rus/91-avatar-the-last-airbender-avatar-legenda-ob-aange.html
  - http://www.animespirit.ru/anime/rs/series-rus/92-avatar-the-last-airbender-2-season-avatar-legenda.html
  - http://www.animespirit.ru/anime/rs/series-rus/9278-krasnyj-belyj-chyornyj-zhyoltyj-rwby.html
  - http://www.animespirit.ru/anime/rs/series-rus/93-avatar-the-last-airbender-avatar-poslednyaya.html
  - http://www.animespirit.ru/anime/rs/series-rus/9342-the-legend-of-korra-2.html
  - http://www.animespirit.ru/anime/rs/special-rus/8937-toriko-x-van-pis-x-drakonij-zhemchug-toriko-x-one.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/7005-poslednyaya-fantaziya-7-yadernyj-krizis-final.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/8092-klassika-yaponskoj-animacii-japanese-anime.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/9491-inuyasya-film-pyatyj-inuyasha-black-tetsusaiga.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/8504-sbornik-istorij-aoyamy-gosyo-ova-2-aoyama-gosho.html
  - http://www.animespirit.ru/anime/rsb/series-russub/8287-pokemon-chyornoe-i-beloe-sudby-sopernikov-pokemon.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/7077-proekt-a-ko-ovy-project-a-ko-ova.html
  - http://www.animespirit.ru/anime/rsb/movie-russub/9668-dazhe-dyavol-mozhet-plakat-2013-cut-scenydmc.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9388-kaprizy-apelsinovoj-ulicy-ova-8-kimagure-orange.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9387-kaprizy-apelsinovoj-ulicy-ova-7-kimagure-orange.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9386-kaprizy-apelsinovoj-ulicy-ova-6-kimagure-orange.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9385-kaprizy-apelsinovoj-ulicy-ova-5-kimagure-orange.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9384-kaprizy-apelsinovoj-ulicy-ova-4-kimagure-orange.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9383-kaprizy-apelsinovoj-ulicy-ova-3-kimagure-orange.html
  - http://www.animespirit.ru/anime/rs/ova-rus/9382-kaprizy-apelsinovoj-ulicy-ova-2-kimagure-orange.html

:ignores_until:
  'http://www.animespirit.ru/anime/rs/series-rus/276-xakkorni-hackroots.html': 2014-08-01

:ignored_in_twice_match:
  - http://www.animespirit.ru/anime/rs/series-rus/4320-naruto-uragannye-xroniki-naruto-shippuuden.html
  - http://www.animespirit.ru/anime/rs/series-rus/33-naruto-uragannye-xroniki-naruto-shippuuden.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4439-naruto-tv-2-naruto-shippuuden.html
  - http://www.animespirit.ru/anime/rsb/series-russub/9685-kosmicheskie-bratya-space-brothers.html
  - http://www.animespirit.ru/anime/rs/series-rus/7494-kosmicheskie-bratya-space-brothers.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7168-oxotnik-x-oxotnik-hunter-x-hunter.html
  - http://www.animespirit.ru/anime/rs/series-rus/6664-oxotnik-x-oxotnik-hunter-x-hunter.html
  - http://www.animespirit.ru/anime/rs/series-rus/1198-fairy-tail-fejri-tejl.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4079-fairy-tail-skazka-o-xvoste-fei-xvost-fei-fejri.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7950-one-piece-van-pis-odnim-kuskom.html
  - http://www.animespirit.ru/anime/rs/series-rus/7948-one-piece-van-pis-odnim-kuskom.html
  - http://www.animespirit.ru/anime/rs/series-rus/191-one-piece-van-pis.html
  - http://www.animespirit.ru/anime/rsb/series-russub/5977-one-piece-van-pis-odnim-kuskom.html
  - http://www.animespirit.ru/anime/rsb/series-russub/2259-dragonboll-zet-dragonball-z-dragon-ball-z.html
  - http://www.animespirit.ru/anime/rs/series-rus/7521-dragonballz-dragonballz.html
  - http://www.animespirit.ru/anime/rs/series-rus/32-naruto-naruto.html
  - http://www.animespirit.ru/anime/rs/series-rus/7564-naruto-naruto.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4438-naruto-naruto.html
  - http://www.animespirit.ru/anime/rs/series-rus/162-shijou-saikyou-no-deshi-kenichi-silnejshij-v.html
  - http://www.animespirit.ru/anime/rsb/series-russub/9581-silnejshij-v-istorii-uchenik-kenichi-shijou.html
  - http://www.animespirit.ru/anime/rs/series-rus/9582-priklyucheniya-korolya-bita-beet-the-vandel.html
  - http://www.animespirit.ru/anime/rsb/series-russub/1221-priklyucheniya-korolya-bita-beet-the-vandel-buster.html
  - http://www.animespirit.ru/anime/rsb/series-russub/9538-kartochnye-vojny-avangard-cardfight-vanguard.html
  - http://www.animespirit.ru/anime/rs/series-rus/4252-kartochnye-vojny-avangard-2011-cardfight-vanguard.html
  - http://www.animespirit.ru/anime/rsb/series-russub/9492-poyopoyo-kansatsu-nikki-xroniki-pufika.html
  - http://www.animespirit.ru/anime/rs/series-rus/7092-poyopoyo-kansatsu-nikki-kot-po-imeni-pojo.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4436-stalnoj-alximik-tv-1-fullmetal-alchemist.html
  - http://www.animespirit.ru/anime/rs/series-rus/15-stalnoj-alximik-fullmetal-alchemist.html
  - http://www.animespirit.ru/anime/rs/series-rus/1298-kaprizy-apelsinovoj-ulicywhimsical-orange-road.html
  - http://www.animespirit.ru/anime/rsb/series-russub/9389-kaprizy-apelsinovoj-ulicy-tv-capricious-orange.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4536-tetrad-smerti-tv-2006-death-note-death.html
  - http://www.animespirit.ru/anime/rs/series-rus/18-death-note-tetrad-smerti.html
  - http://www.animespirit.ru/anime/rsb/series-russub/9367-rave-master-ryejv-master.html
  - http://www.animespirit.ru/anime/rs/series-rus/367-rave-master-ryejv-master.html
  - http://www.animespirit.ru/anime/rs/series-rus/9308-dragonboll-dragon-ball.html
  - http://www.animespirit.ru/anime/rsb/series-russub/2056-dragonboll-dragon-ball.html
  - http://www.animespirit.ru/anime/rs/series-rus/9067-torikotoriko.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7159-toriko-toriko.html
  - http://www.animespirit.ru/anime/rs/series-rus/5101-toriko-toriko.html
  - http://www.animespirit.ru/anime/rsb/series-russub/2329-detektiv-konan-detective-conan.html
  - http://www.animespirit.ru/anime/rs/series-rus/6655-detektiv-konan-detective-conan.html
  - http://www.animespirit.ru/anime/rs/series-rus/4878-xayatye-boevoj-dvoreckij-tv-1-hayate-no-gotoku.html
  - http://www.animespirit.ru/anime/rsb/series-russub/149-xayatye-boevoj-dvoreckij-hayate-no-gotoku.html
  - http://www.animespirit.ru/anime/rs/series-rus/231-mobile-suit-gundam-seed-mobilnyj-dospex-gandam.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6183-mobilnyj-voin-gandam-pokolenie-kidou-senshi.html
  - http://www.animespirit.ru/anime/rs/series-rus/4860-cket-dyens-.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7293-cket-dyens-sket-dance-zakruzhimsya-so-sket.html
  - http://www.animespirit.ru/anime/rs/series-rus/547-stalnoj-alximik-vtoroj-sezon-full-metal-alchemist.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4434-stalnoj-alximik-tv-2-fullmetal-alchemist.html
  - http://www.animespirit.ru/anime/rs/series-rus/5899-odinnadcat-molnij-inazuma-eleven-ozvuchka.html
  - http://www.animespirit.ru/anime/rsb/series-russub/2587-odinnadcat-molnij-inazuma-eleven.html
  - http://www.animespirit.ru/anime/rs/ova-rus/6614-legenda-o-geroyax-galaktiki-ova-1-legend-of-the.html
  - http://www.animespirit.ru/anime/rsb/ova-russub/3387-legenda-o-geroyax-galaktiki-ova-1-legend-of-the.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6558-yugio-tv-3-yu-gi-oh-gx-yu-gi-oh-duel-monster-gx.html
  - http://www.animespirit.ru/anime/rs/series-rus/6556-yugio-tv-3-yu-gi-oh-gx-yu-gi-oh-duel-monster-gx.html
  - http://www.animespirit.ru/anime/rsb/series-russub/1915-yu-gi-oh-duel-monsters-yu-gi-o-duyelnye-monstry.html
  - http://www.animespirit.ru/anime/rs/series-rus/6194-yugiotv-2-yu-gi-oh-duel-monsters-yuu-gi-ou-duel.html
  - http://www.animespirit.ru/anime/rs/series-rus/1844-ranma-12-ranma-12.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7133-ranma-12-tv-ranma-12.html
  - http://www.animespirit.ru/anime/rsb/series-russub/5968-yugio-duyelnye-monstry-yuu-gi-ou-zexal.html
  - http://www.animespirit.ru/anime/rs/series-rus/6856-yu-gi-oh-zexal-yuu-gi-ou-zexal-yu-gi-o-zeal.html
  - http://www.animespirit.ru/anime/rs/series-rus/7113-povest-o-sosedyax-tv-gokinjo-monogatari.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6858-povest-o-sosedyax-tv-gokinjo-monogatari.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7550-milyj-dom-ti-tv-2-chis-new-address-chis-sweet.html
  - http://www.animespirit.ru/anime/rs/series-rus/7549-milyj-dom-ti-tv-2-chis-new-address.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7550-milyj-dom-ti-tv-2-chis-new-address-chis-sweet.html
  - http://www.animespirit.ru/anime/rs/series-rus/7549-milyj-dom-ti-tv-2-chis-new-address.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7551-chis-sweet-home-milyj-dom-chii.html
  - http://www.animespirit.ru/anime/rs/series-rus/352-chis-sweet-home-milyj-dom-chii.html
  - http://www.animespirit.ru/anime/rs/series-rus/1000-strannik-kenshin-brodyaga-kyensin-rurouni-kenshin.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6847-brodyaga-kyensin-samurai-x-rurouni-kenshin-meiji.html
  - http://www.animespirit.ru/anime/rs/series-rus/7179-gintama-tv-2-gintama.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4588-gintama-tv-2-gintama.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4215-beelzebub-velzevul-tv.html
  - http://www.animespirit.ru/anime/rs/series-rus/6649-velzepuz-tv-beelzebub.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4498-blich-bleach.html
  - http://www.animespirit.ru/anime/rs/series-rus/224-blich-bleach.html
  - http://www.animespirit.ru/anime/rs/series-rus/7229-danbooru-senki-danbooru-senki.html
  - http://www.animespirit.ru/anime/rsb/series-russub/7219-velikaya-bitva-v-kartonnoj-korobke-cardboard-war.html
  - http://www.animespirit.ru/anime/rsb/series-russub/4243-nebesa-mar-marchen-awakens-romance-mar-heaven.html
  - http://www.animespirit.ru/anime/rs/series-rus/4629-nebesa-mar-marchen-awakens-romance-mar-heaven.html
  - http://www.animespirit.ru/anime/rs/series-rus/6485-steklyannaya-maska-tv-2-garasu-no-kamen-tv-2.html
  - http://www.animespirit.ru/anime/rsb/series-russub/1420-steklyannaya-maska-tv-2garasu-no-kamen.html
  - http://www.animespirit.ru/anime/rs/series-rus/6559-boku-wa-tomodachi-ga-sukunai-klub-sosedej.html
  - http://www.animespirit.ru/anime/rs/ova-rus/6665-boku-wa-tomodachi-ga-sukunai-klub-sosedej-ova.html
  - http://www.animespirit.ru/anime/rs/series-rus/7002-kekkaishi.html
  - http://www.animespirit.ru/anime/rsb/series-russub/1775-zagraditeli-kekkaishi.html
  - http://www.animespirit.ru/anime/rs/series-rus/4891-chudnye-veshhi-hyouge-mono.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6873-chudnye-veshhi-hyouge-mono-komichnaya-lichnost.html
  - http://www.animespirit.ru/anime/rs/series-rus/785-nana-tv-nana.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6486-nana-nana.html
  - http://www.animespirit.ru/anime/rsb/series-russub/1359-koshachi-istorii-2009-kuruneko.html
  - http://www.animespirit.ru/anime/rs/series-rus/6605-kuruneko-koshachi-istorii.html
  - http://www.animespirit.ru/anime/rs/series-rus/6810-ukrotiteli-digimonov-digimon-tamers.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6809-ukrotiteli-digimonov-digimon-tamers.html
  - http://www.animespirit.ru/anime/rs/series-rus/6623-strastnoe-cerdce-dikij-bombardir-hungry-heart.html
  - http://www.animespirit.ru/anime/rsb/series-russub/1111-neistovyj-bombardir-hungry-heart-wild-striker.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6618-spasateli-digimonov-digimon-savers.html
  - http://www.animespirit.ru/anime/rs/series-rus/6617-spasateli-digimonov-digimon-savers.html
  - http://www.animespirit.ru/anime/rs/series-rus/6474-mobilnyj-voin-zeta-gandam-mobile-suit-zeta-gundam.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6137-mobilnyj-voin-zeta-gandam-mobile-suit-zeta-gundam.html
  - http://www.animespirit.ru/anime/rs/series-rus/232-gundam-seed-destiny-mobilnyj-dospex-gandam-sudba.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6184-mobilnyj-voin-gandam-sudba-pokoleniya-mobile-suit.html
  - http://www.animespirit.ru/anime/rs/series-rus/3408-mobilnyj-gandam-dubl-vye-mobile-suit-gundam-wing.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6166-mobilnyj-gandam-dubl-vye-mobile-suit-gundam-wing.html
  - http://www.animespirit.ru/anime/rs/series-rus/6473-mobilnyj-voin-gandam-0079-kidou-senshi-gundam.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6116-mobilnyj-voin-gandam-0079-kidou-senshi-gundam.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6191-yevrika-7-psalmy-planet-eureka-seven-psalms-of.html
  - http://www.animespirit.ru/anime/rs/series-rus/342-yevrika-7-psalmy-planet-eureka-seven-psalms-of.html
  - http://www.animespirit.ru/anime/rsb/series-russub/6404-yunaya-revolyucionerka-utyena-tv-revolutionary.html
  - http://www.animespirit.ru/anime/rs/series-rus/343-revolutionary-girl-utena-yunaya-revolyucionerka.html
