default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: "94520d30-a390-427b-bb67-f785847518dc"

  # Your app's name
  name: "App"

  # Actions that should not be monitored by AppSignal
  # ignore_actions:
  #   - ApplicationController#isup

  # See http://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

  ignore_errors:
    - AbstractController::ActionNotFound
    - ActionController::InvalidAuthenticityToken
    - ActionController::RoutingError
    - ActionController::UnknownFormat
    - ActionController::UnknownHttpMethod
    - ActionDispatch::RemoteIp::IpSpoofAttackError
    - ActiveRecord::PreparedStatementCacheExpired
    - ActiveRecord::RecordNotFound
    - CanCan::AccessDenied
    - I18n::InvalidLocale
    - Unicorn::ClientShutdown
    - Unauthorized
    - AgeRestricted
    - MismatchedEntries
    - InvalidEpisodesError
    - CopyrightedResource
    - Net::SMTPServerBusy
    - Net::SMTPFatalError
    - Interrupt
    - Apipie::ParamMissing
    - InvalidIdError
    - InvalidParameterError
    - EmptyContentError
    - MalParser::RecordNotFound
    - BadImageError
    - Errors::NotIdentifiedByImageMagickError
    - Sidekiq::Shutdown
    - Terrapin::ExitStatusError

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
beta:
  <<: *defaults
  active: false

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
