default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: '9185649b-2890-4c72-8694-ec567fd3e2d4'

  # Your app's name
  name: 'App V2'

  # Actions that should not be monitored by AppSignal
  # ignore_actions:
  #   - ApplicationController#isup

  # Errors that should not be recorded by AppSignal
  # For more information see our docs:
  # https://docs.appsignal.com/ruby/configuration/ignore-errors.html
  ignore_errors:
    - AbstractController::ActionNotFound
    - ActionController::InvalidAuthenticityToken
    - ActionController::RoutingError
    - ActionController::UnknownFormat
    - ActionController::UnknownHttpMethod
    - ActionDispatch::RemoteIp::IpSpoofAttackError
    - ActiveRecord::PreparedStatementCacheExpired
    - ActiveRecord::RecordNotFound
    - CanCan::AccessDenied
    - I18n::InvalidLocale
    - Unicorn::ClientShutdown
    - Unauthorized
    - AgeRestricted
    - MismatchedEntries
    - InvalidEpisodesError
    - CopyrightedResource
    - Net::SMTPServerBusy
    - Net::SMTPFatalError
    - Interrupt
    - Apipie::ParamMissing
    - InvalidIdError
    - InvalidParameterError
    - EmptyContentError
    - MalParser::RecordNotFound
    - BadImageError
    - Errors::NotIdentifiedByImageMagickError
    - Sidekiq::Shutdown
    - Terrapin::ExitStatusError

  # See http://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
beta:
  <<: *defaults
  active: false

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
