default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: "54021518-b80c-4904-88b5-8e4169602a93"

  # Your app's name
  name: "shiki"

  # Actions that should not be monitored by AppSignal
  # ignore_actions:
  #   - ApplicationController#isup

  # See http://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
beta:
  <<: *defaults
  active: false

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: false
