development: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DB'] || 'shikimori_production' %>
  username: <%= ENV['POSTGRES_USER'] || 'shikimori_production' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  pool: 100
  timeout: 5000
  encoding: utf8
  collation: ru_RU.UTF-8
  ctype: ru_RU.UTF-8
  template: template0

production:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['PGDATABASE'] || "shikimori_test_#{ENV['TEST_ENV_NUMBER']}" %>
  username: <%= ENV['PGUSER'] || 'shikimori_test' %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
