development: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['PGDATABASE'] || 'shikimori_production' %>
  username: <%= ENV['PGUSER'] || 'shikimori_production' %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
  pool: 100
  timeout: 5000

production:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['PGDATABASE'] || "shikimori_test_#{ENV['TEST_ENV_NUMBER']}" %>
  username: <%= ENV['PGUSER'] || 'shikimori_test' %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
