# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development: &defaults
  adapter: postgresql
  encoding: utf8
  database: shikimori_production
  username: shikimori_production
  password: bimpQscuJvkkL4Y
  host: localhost
  pool: 100
  timeout: 5000

production:
  <<: *defaults

test:
  <<: *defaults
  database: shikimori_test
  username: shikimori_test
  password: bimpQscuJvkkL4Y
