---
:ignores:
  - the_dreams_of_jinsha
  - the_last_airbender__the_legend_of_korra_first_book_air
  - maou_from_now_on___tv_2 # первый и второй сезона на шики слиты в одно аниме
  - gekijouban_doubutsu_no_mori
  - the_making_of_kuroshitsuji_ii_ova_3
  - what_s_up__human
  - azureus_rising
  - fukumoto_s_thirteen
  - shakugan_no_shana_ova # какой-то второстепенный спешл, непонятно, куда его приткнуть
  - thundercats # хз что это
  - mobile_suit_gundam_x # такого 39 серийного гандама в базе
  - pokemon_black_and_white_rival_destinies # 38 серийного покемона не нашёл в базе
  - toriko_x_one_piece_x_dragon_ball
  - final_fantasy_vii_crisis_core_movie
  - final_fantasy_vii__dirge_of_cerberus
  - japanese_anime_classic_collection
  - doraemon_and_the_robot_of_bugs__mini
  - lensman__secret_of_the_lens
  - codehunters
  - street_fighter_alpha_2
  - magical_princess_minky_momo_hitomi_no_seiza_minky_momo_song_special
  - kodomo_no_jikan__kodomo_no_natsu_jikan
  - lady_death__the_motion_picture
  - break_through_heaven_gurren_lagann__crimson_chapte
  - love_live__school_idol_project
  - glass_no_clair___ginga_tetsudo_999__1980

  # дубликат
  - arve_rezzle__kikaijikake_no_yoseitachi
  - onii_chan_dakedo_ai_sae_areba_kankei_nai_yo_ne
  - toriko_tv_2
  - pokemon_black_and_white
  - ghost_in_the_shell__stand_alone_complex_2002
  - battle_angel_alita
  - boundary_of_emptiness__overlooking_view
  - yumeiro_patissiere_2009
  - juusou_kikou_dancouga_nova
  - the_big_o_s1
  - mobile_suit_gundam_seed
  - infinite_ryvius_1999
  - kishin_doji_zenki
  - new_fist_of_the_north_star_ova_1
  - street_fighter_iv__arata_naru_kizuna
  - to_elliptical_orbit___symbiotic_planet
  - mobile_suit_gundam_wing_1995
  - natsuiro_no_sunadoke
  - kateikyoushi_hitman_reborn__ova
  - training_with_hinako
  - lost_chapter_of_the_stars___birth

  # не аниме
  - rwby
  - level_up
  - avatar__the_last_airbender
  - avatar__the_last_airbender_2004
  - avatar__the_last_airbender__2_season
  - the_legend_of_korra__2_season
  - dead_space__downfall
  - wakfu
  - mini_wakfu
  - wakfu__tb_2
  - pieklo_dantego
  - exaella
  - dragons_ii__the_metal_ages
  - sintel
  - amv_hell_4__the_last_one
  - life

  # не нашёл
  - shinryaku___ika_musume_ova
  - grappler_baki_ova
  - meguriau_sekai
  - maho_shojo_pretty_sammy_ova
  - shin_hokuto_no_ken_ova_2_2007
  - black_jack_final
  - shin_hokuto_no_ken_ova_2
  - robotech
  - you_re_under_arrest__taiho_shichau_zo
  - naruto_ova_1__2
  - seitokai_yakuindomo___kaette_kita_seitokai_yakuindomo
  - bishoujo_senshi_sailor_moon__2013
  - kodomo_no_jikan
  - macross_ii_the_movie_edition__lovers_again
  - neko_no_shuukai
  - ayu_mayu_theater_ova
  - mobile_suit_gundam_seed__movie_ii___the_far_away_dawn
  - mobile_suit_gundam_seed__movie_iii___the_rumbling_sky
  - shingeki_no_kyojin_ova_2
  - otona_joshi_no_anime_time_2__yuuge
  - otona_joshi_no_anime_time_2__jinsei_best_10
  - otona_joshi_no_anime_time_2__dokoka_de_wa_nai_koko
  - dr__slump___arale_chan_ncha__trembling_hot_summer_holiday
  - gintama__ova_2____birth_of_white_demon
  - gall_force_4

  # руками залить видео:
  # 5578
  - aoyama_gosho_short_story_collection_ova_1
  - aoyama_gosho_short_story_collection_ova_2
  # 9445
  - gunparade_orchestra_ova_1
  - gunparade_orchestra_ova_2
  - gunparade_orchestra_ova_3
  # http://shikimori.org/animes/type/Special/search/+Sailor+Moon
  - sailor_moon_special_movies
  # http://shikimori.org/animes/search/Runner+Kuromi
  - animation_runner_kuromi_1_2
  # http://shikimori.org/animes/15489-Yu-Gi-Oh-Zexal-Second
  # тут сразу и второй сезон, и первый
  - yu_gi_oh__duel_monsters__tv_2
  # http://shikimori.org/animes/9136-Kuroshitsuji-II-Specials
  - kuroshitsuji_ii___the_tale_of_will_the_shinigami_ova_5
  - kuroshitsuji_ii__welcome_to_the_phantomhives_ova_2
  - kuroshitsuji_ii__ciel_in_wonderland___ova_1__4
  # http://shikimori.org/animes/12929-Saint-Seiya-Omega - у аниме ниже серии начинаются с 50+
  - saint_seiya_omega__new_cloth_hen
  # http://shikimori.org/animes/1168-Musekinin-Kanchou-Tylor-OVA сюда влить три нижних
  - irresponsible_captain_tylor___from_here_to_eternity
  - the_irresponsible_captain_tylor___an_exceptional_episode
  - irresponsible_captain_tylor___sidestory_collection
  # http://shikimori.org/animes/1935-Megazone-23
  - megazone_23
  - megazone_23_part_2
  - megazone_23_part_iii
  # http://shikimori.org/animes/1072-Sweat-Punch
  - dan_petory_kyoushu_no_yuuutsu__sweat_punch_series_1
  - higan__sweat_punch_series_4
  - end_of_the_world__sweat_punch_series_2
  - junk_town
  - kigeki__sweat_punch_series_3
  # http://shikimori.org/animes/2696-Crusher-Joe-1989
  - crusher_joe__saishuu_heiki_ash
  - crusher_joe__hyouketsu_kangoku_no_wana
  # http://shikimori.org/animes/2294-Mobile-Suit-Gundam-Seed-Destiny-Special-Edition
  - mobile_suit_gundam_seed_destiny_special_edition_iii__the_hell_fire_of_destiny
  - mobile_suit_gundam_seed_destiny_special_edition_iv__the_cost_of_freedom
  - mobile_suit_gundam_seed_destiny_special_edition_i__the_broken_world
  - mobile_suit_gundam_seed_destiny_special_edition_ii__respective_swords

# временно игнорируемое: аниме, которые в дальнейшем могут появиться в базе шики
:ignores_until:
  k_2nd_season: 2014-01-01
  psycho_pass_2: 2014-01-01

:ignored_in_twice_match:
  - one_piece
  - one_piece__tv
  - fairy_tail
  - fairy_tail__tv_1
  - kissxsis_ova
  - kissxsis__ova
  - fairy_tail_ecchi_ova
  - fairy_tail__ova
  - kemeko_deluxe___tv
  - the_unknown_girlfriend_kemeko__tv
  - bokusatsu_tenshi_dokuro_chan
  - club_to_death_angel_dokuro_chan__ova_1
  - bokusatsu_tenshi_dokuro_chan_2nd_series
  - club_to_death_angel_dokuro_chan_second__ova_2
  - hellsing_ultimate
  - hellsing_ultimate__ova
  - blue_exorcist
  - blue_exorcist__tv
  - gekijouban_ao_no_exorcist
  - blue_exorcist__the_movie
  - to_love_ru
  - to_love_ru__trouble
  - shakugan_no_shana_s
  - shana_of_the_burning_eyes_s__ova_2
  - bokusatsu_tenshi_dokuro_chan_2nd_series
  - club_to_death_angel_dokuro_chan_second__ova_2
  - mekaku_city_actors
  - mekakucity_actors
  - jojo_s_bizarre_adventure__tv
  - jojo_s_bizarre_adventure__tv_1
  - tengen_toppa_gurren_lagann
  - heavenly_breakthrough_gurren_lagann__tv
  - history_s_strongest_disciple_kenichi__ova
  - shijou_saikyou_no_deshi_kenichi_ova
  - saint_seiya_tv
  - knights_of_the_zodiac
  - hanasaku_iroha__home_sweet_home
  - hanasaku_iroha__home_sweet_home__movie
  - chuunibyou_demo_koi_ga_shitai
  - love__chunibyo___other_delusions__tv_1
  - senyuu
  - prowess__ona_1
  - senyuu__2
  - prowess__ona_2
  - little_busters_ex
  - little_busters_ex__ova
  - i_m_absolutely_not_in_love_with_my_brother__so_there
  - i_m_absolutely_not_in_love_with_my_brother__so_there____tv
  - ranma_1_2
  - ranma_1_2_movie
  - naruto_sd__rock_lee_no_seishun_full_power_ninden_tv
  - naruto_spin_off__rock_lee___his_ninja_pals
  - toradora
  - tiger_x_dragon
  - accel_world
  - accel_world__tv
  - samurai7
  - samurai_7
  - to_aru_kagaku_no_railgun
  - a_certain_scientific_railgun__tv_1
  - kyoukai_senjou_no_horizon_2
  - horizon_in_the_middle_of_nowhere_ii__tv_2
  - toaru_majutsu_no_index_ii
  - a_certain_magical_index_ii__tv_2
  - grenadier_the_smiling_warrior
  - grenadier_the_beautiful_warrior
  - rosario___vampire_capu2
  - rosario___vampire_capu2__tv_2
  - jungle_wa_itsumo_hare_nochi_guu
  - jungle_wa_itsumo_hare_nochi_guu_final
  - bleach__the_hell_verse
  - bleach_the_movie_4___the_hell_verse
  - hetalia__the_beautiful_world
  - hetalia__the_beautiful_world__tv_3
  - high_school_dxd
  - high_school_dxd__tv_1
  - haiyore__nyaruko_san_w
  - nyarko_san__another_crawling_chaos_w__tv_2
  - bleach
  - bleach_tv
  - aria_the_scarlet_ammo_ova
  - aria_the_scarlet_ammo__ova
  - date_a_live_ova
  - date_a_live__ova
  - code_geass__lelouch_of_the_rebellion
  - code_geass__lelouch_of_the_rebellion__tv_1
  - death_note_anime_director_s_cut_final_conclusion
  - death_note__the_movie____final_conclusion
  - a_certain_magical_index_the_movie
  - a_certain_magical_index__movie
  - freezing_vibration
  - freezing_vibration__tv_2
  - valvrave_the_liberator_2
  - valvrave_the_liberator__tv_2
  - aoki_hagane_no_arpeggio__ars_nova
  - arpeggio_of_blue_steel__tv
  - haiyore__nyaruko_san_w
  - nyarko_san__another_crawling_chaos_w__tv_2
  - rescue_me
  - liberabit_me___ova
  - freezing
  - fullmetal_alchemist
  - fullmetal_alchemist__tv_1
  - freezing__tv_1
  - high_school_dxd
  - high_school_dxd__tv_1
  - oda_nobuna_no_yabou
  - the_ambition_of_oda_nobuna
  - high_school_dxd_2
  - high_school_dxd_new__tv_2
  - hetalia_world_series
  - hetalia_world_series__tv_2
  - magi__the_labyrinth_of_magic
  - magi__the_labyrinth_of_magic__tv_1
  - toradora
  - tiger_x_dragon
  - strike_witches_tv
  - strike_witches__tv_1
  - code__breaker_ova
  - genshiken_nidaime_no_roku
  - sora_no_otoshimono
  - lost_property_of_the_sky__tv_1
  - valvrave_the_liberator
  - valvrave_the_liberator__tv_1
  - accel_world
  - accel_world__tv
  - problem_children_are_coming_from_another_world__aren_t_they_____ova
  - problem_children_are_coming_from_another_world__aren_t_they___ova
  - hidan_no_aria
  - aria_the_scarlet_ammo__tv
  - to_love_ru__darkness
  - to_love_ru_trouble___darkness
  - date_a_live
  - date_a_live__tv_1
  - hagure_yuusha_no_estetica
  - aesthetica_of_a_rogue_hero
  - maji_de_watashi_ni_koi_shinasai
  - love_me__seriously___tv
  - to_love_ru_ova
  - to_love_ru__trouble_ova
  - girls_und_panzer
  - girls___panzers__tv
  - akb0048_next_stage
  - akb0048_next_stage__tv_2
  - black_rock_shooter_tv
  - black_rock_shooter__tv
  - problem_children_are_coming_from_another_world__aren_t_they
  - problem_children_are_coming_from_another_world__aren_t_they___tv
  - natsume_yuujinchou
  - natsume_s_book_of_friends
  - to_aru_kagaku_no_railgun_ova
  - a_certain_scientific_railgun__ova
  - maken_ki__ova
  - maken_ki___ova
  - saint_knight_story_in_an_alternate_world
  - saint_knight_story_in_an_alternate_world__ova
  - rosario___vampire_capu2
  - rosario___vampire_capu2__tv_2
  - black_rock_shooter
  - black_rock_shooter__ova
  - gakuen_mokushiroku__high_school_of_the_dead___drifters_of_the_dead
  - high_school_of_the_dead___drifters_of_the_dead__ova
  - gekijouban_gintama__shinyaku_benizakura_hen
  - gintama__movie_1
  - hana_saku_iroha
  - hana_saku_iroha__tv_1
  - seikon_no_qwaser__jotei_no_shouzou
  - the_qwaser_of_stigmata___portrait_of_the_empress
  - kyoukai_no_kanata
  - beyond_the_boundary
  - fairy_tail___the_maiden_of_the_phoenix
  - fairy_tail__movie_1____the_maiden_of_the_phoenix
  - majin_tantei_nougami_neuro
  - neuro__supernatural_detective
  - kissxsis_tv
  - kissxsis__tv
  - suzumiya_haruhi_no_yuuutsu
  - the_melancholy_of_haruhi_suzumiya_2
  - to_aru_kagaku_no_railgun_s
  - a_certain_scientific_railgun_s__tv_2
  - otome_youkai_zakuro
  - girl_demon_zakuro
  - hellsing
  - hellsing__tv
  - fullmetal_alchemist__premium_collection
  - fullmetal_alchemist__ova____premium_collection
  - my_little_sister_can_t_be_this_cute
  - my_little_sister_can_t_be_this_cute__tv_2
  - r_15
  - r_15__tv
  - fullmetal_alchemist__brotherhood___4_koma_theater
  - fullmetal_alchemist__brotherhood___4_koma_theater__extra
  - asatte_no_houkou
  - living_for_the_day_after_tomorrow
  - one_piece__dead_end
  - one_piece__movie_4____dead_end
  - ikkitosen__legendary_fighter
  - ikkitousen__legendary_fighter
  - one_piece__movie_11
  - one_piece__movie_11____film_z
  - naruto_movie_9___road_to_ninja
  - naruto__hurricane_chronicles__movie_9____road_to_ninja
  - aoi_sekai_no_chuushin_de
  - in_the_center_of_the_blue_world__tv
  - kimi_ga_aruji_de_shitsuji_ga_ore_de__they_are_my_noble_masters
  - you_are_the_master_and_the_servant_is_me__tv
  - kimi_ga_aruji_de_shitsuji_ga_ore_de__they_are_my_noble_masters
  - you_are_the_master_and_the_servant_is_me__tv
  - utawarerumono
  - shadow_warrior_chronicles
  - hunter_x_hunter___g_i_final
  - hunter_x_hunter__greed_island_final
  - spice_and_wolf_ii_ova
  - the_wolf_and_the_amber_melancholy
  - seikon_no_qwaser
  - the_qwaser_of_stigmata__tv_1
  - seikon_no_qwaser_ii
  - the_qwaser_of_stigmata__tv_2
  - hanaukyo_maids
  - hanaukyo_maids__tv_1
