---
:ignores:
  - the_last_airbender__the_legend_of_korra_first_book_air
  - maou_from_now_on___tv_2 # первый и второй сезона на шики слиты в одно аниме
  - gekijouban_doubutsu_no_mori
  - the_making_of_kuroshitsuji_ii_ova_3
  - what_s_up__human
  - azureus_rising
  - fukumoto_s_thirteen
  - shakugan_no_shana_ova # какой-то второстепенный спешиал, непонятно, куда его приткнуть
  - thundercats # хз что это
  - mobile_suit_gundam_x # такого 39 серийного гандама в базе
  - pokemon_black_and_white_rival_destinies # 38 серийного покемона не нашёл в базе
  - toriko_x_one_piece_x_dragon_ball
  - final_fantasy_vii_crisis_core_movie
  - final_fantasy_vii__dirge_of_cerberus
  - japanese_anime_classic_collection
  - doraemon_and_the_robot_of_bugs__mini
  - lensman__secret_of_the_lens
  - codehunters
  - street_fighter_alpha_2
  - magical_princess_minky_momo_hitomi_no_seiza_minky_momo_song_special
  - kodomo_no_jikan__kodomo_no_natsu_jikan
  - lady_death__the_motion_picture
  - break_through_heaven_gurren_lagann__crimson_chapte
  - love_live__school_idol_project
  - glass_no_clair___ginga_tetsudo_999__1980

  # дубликат
  - arve_rezzle__kikaijikake_no_yoseitachi
  - onii_chan_dakedo_ai_sae_areba_kankei_nai_yo_ne
  - toriko_tv_2
  - pokemon_black_and_white
  - ghost_in_the_shell__stand_alone_complex_2002
  - battle_angel_alita
  - boundary_of_emptiness__overlooking_view
  - yumeiro_patissiere_2009
  - juusou_kikou_dancouga_nova
  - the_big_o_s1
  - mobile_suit_gundam_seed
  - infinite_ryvius_1999
  - kishin_doji_zenki
  - new_fist_of_the_north_star_ova_1
  - street_fighter_iv__arata_naru_kizuna
  - to_elliptical_orbit___symbiotic_planet
  - mobile_suit_gundam_wing_1995

  # не аниме
  - rwby
  - level_up
  - avatar__the_last_airbender
  - avatar__the_last_airbender_2004
  - avatar__the_last_airbender__2_season
  - the_legend_of_korra__2_season
  - dead_space__downfall
  - wakfu
  - mini_wakfu
  - wakfu__tb_2
  - pieklo_dantego
  - exaella
  - dragons_ii__the_metal_ages
  - sintel
  - amv_hell_4__the_last_one
  - life

  # не нашёл
  - shinryaku___ika_musume_ova
  - grappler_baki_ova
  - meguriau_sekai
  - maho_shojo_pretty_sammy_ova
  - shin_hokuto_no_ken_ova_2_2007
  - black_jack_final
  - shin_hokuto_no_ken_ova_2
  - robotech
  - you_re_under_arrest__taiho_shichau_zo

  # руками залить видео для:
  # 5578
  - aoyama_gosho_short_story_collection_ova_1
  - aoyama_gosho_short_story_collection_ova_2
  # 9445
  - gunparade_orchestra_ova_1
  - gunparade_orchestra_ova_2
  - gunparade_orchestra_ova_3
  # http://shikimori.org/animes/type/Special/search/+Sailor+Moon
  - sailor_moon_special_movies
  # http://shikimori.org/animes/search/Runner+Kuromi
  - animation_runner_kuromi_1_2
  # http://shikimori.org/animes/15489-Yu-Gi-Oh-Zexal-Second
  # тут сразу и второй сезон, и первый
  - yu_gi_oh__duel_monsters__tv_2
  # http://shikimori.org/animes/9136-Kuroshitsuji-II-Specials
  - kuroshitsuji_ii___the_tale_of_will_the_shinigami_ova_5
  - kuroshitsuji_ii__welcome_to_the_phantomhives_ova_2
  - kuroshitsuji_ii__ciel_in_wonderland___ova_1__4
  # http://shikimori.org/animes/12929-Saint-Seiya-Omega - у аниме ниже серии начинаются с 50+
  - saint_seiya_omega__new_cloth_hen
  # http://shikimori.org/animes/1168-Musekinin-Kanchou-Tylor-OVA сюда влить три нижних
  - irresponsible_captain_tylor___from_here_to_eternity
  - the_irresponsible_captain_tylor___an_exceptional_episode
  - irresponsible_captain_tylor___sidestory_collection
  # http://shikimori.org/animes/1935-Megazone-23
  - megazone_23
  - megazone_23_part_2
  - megazone_23_part_iii


# временно игнорируемое: аниме, которые в дальнейшем могут появиться в базе шики
:ignores_until:
  k_2nd_season: 2014-01-01
  psycho_pass_2: 2014-01-01
