---
:ignores:
  - the_last_airbender__the_legend_of_korra_first_book_air
  - maou_from_now_on___tv_2 # первый и второй сезона на шики слиты в одно аниме
  - gekijouban_doubutsu_no_mori
  - rwby # не аниме
  - the_making_of_kuroshitsuji_ii_ova_3
  - what_s_up__human
  - azureus_rising
  - fukumoto_s_thirteen
  - mobile_suit_gundam_x # хз что это такое, не нахожу такого 39серийного гандама в базе
  - dead_space__downfall # не аниме
  - wakfu__tb_2 # не аниме
  - shakugan_no_shana_ova # какой-то второстепенный спешиал, непонятно, куда его приткнуть

# временно игнорируемое: аниме, которые в дальнейшем могут появиться в базе шики
:ignores_until:
  k_2nd_season: 2014-01-01
  psycho_pass_2: 2014-01-01
