---
api_key: 4b4f97c8
development_environments:
  - development
  - test
exceptions:
  ignore:
    - CanCan::AccessDenied
    - ActionController::InvalidAuthenticityToken
    - ActionController::UnknownFormat
    - ActionDispatch::RemoteIp::IpSpoofAttackError
    - ActiveRecord::RecordNotFound
    - I18n::InvalidLocale
    - Unicorn::ClientShutdown
    - NotFound
    - Unauthorized
    - Forbidden
    - AgeRestricted
    - MismatchedEntries
    - CopyrightedResource
    - Net::SMTPServerBusy
    - Net::SMTPFatalError
    - Interrupt
    - Apipie::ParamMissing
metrics:
  enabled: false
traces:
  enabled: false
