---
api_key: 'bcef3044'
development_environments:
  - 'development'
  - 'test'
exceptions:
  ignore:
    - 'CanCan::AccessDenied'
    - 'NotFound'
    - 'Unauthorized'
    - 'Forbidden'
    - 'ActionController::InvalidAuthenticityToken'
    - 'ActionController::UnknownFormat'
    - 'ActiveRecord::RecordNotFound'
