---
api_key: 'eba15fbe'
development_environments:
  - 'development'
  - 'test'
exceptions:
  ignore:
    - 'CanCan::AccessDenied'
    - 'NotFound'
    - 'Unauthorized'
    - 'Forbidden'
    - 'AgeRestricted'
    - 'ActionController::InvalidAuthenticityToken'
    - 'ActionController::UnknownFormat'
    - 'ActiveRecord::RecordNotFound'
    - 'Unicorn::ClientShutdown'
    - 'MismatchedEntries'
