---
api_key: 459e884c
development_environments:
  - development
  - test
exceptions:
  ignore:
    - CanCan::AccessDenied
    - ActionController::InvalidAuthenticityToken
    - ActionController::UnknownFormat
    - ActionDispatch::RemoteIp::IpSpoofAttackError
    - ActiveRecord::RecordNotFound
    - I18n::InvalidLocale
    - Unicorn::ClientShutdown
    - NotFound
    - Unauthorized
    - Forbidden
    - AgeRestricted
    - MismatchedEntries
    - CopyrightedResource
    - Net::SMTPServerBusy
