development: &defaults
  a822ef3jkhdf67yhjknfsd786tzhjklcr987ftyvaghdsjh34t7689uhfsddjsb126387uirufgs5dfbhjkeds67ftvuhjas78d6yuad906f5bb5f053ad5a310580b2

test: *defaults

staging: *defaults

production: *defaults
