:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 5

production:
  :concurrency: 8

:queues:
  - default
  - cpu_intensive
  - slow_parsers
  - [critical, 5]

:limits:
  cpu_intensive: 1
  slow_parsers: 2
