:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 5

production:
  :concurrency: 60

:queues:
  - [high_priority, 8]
  - [critical, 10]
  - [push_notifications, 2]
  - [default, 5]
  - [cpu_intensive, 5]
  - [slow_parsers, 5]
  - [torrents_parsers, 5]
  - [mal_parsers, 3]
  - [anime_online_parsers, 5]
  - [manga_online_parsers, 5]
  - [webm_thumbnails, 5]
  - [similar_users, 5]
  - [low_priority, 1]
  - [mailers, 5]
  - [imports, 4]
  - [achievements, 6]

:limits:
  cpu_intensive: 2
  slow_parsers: 2
  torrents_parsers: 1
  anime_online_parsers: 1
  manga_online_parsers: 1
  webm_thumbnails: 1
  similar_users: 1
  mal_parsers: 50
  push_notifications: 5
  imports: 2
