:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 5

production:
  :concurrency: 12

:queues:
  - [high_priority, 3]
  - [critical, 6]
  - [push_notifications, 2]
  - default
  - cpu_intensive
  - slow_parsers
  - torrents_parsers
  - anime_online_parsers
  - manga_online_parsers
  - webm_thumbnails
  - similar_users

:limits:
  cpu_intensive: 2
  slow_parsers: 2
  torrents_parsers: 1
  anime_online_parsers: 1
  manga_online_parsers: 1
  webm_thumbnails: 1
  similar_users: 1
