:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 5

production:
  :concurrency: 12

:queues:
  - default
  - cpu_intensive
  - slow_parsers
  - torrents_parsers
  - [critical, 6]

:limits:
  cpu_intensive: 2
  slow_parsers: 2
  torrents_parsers: 1
