---
-
  - A17819 # Kyoto Animation: Suiei-hen
  - A18507 # Free!
-
  - A17813 # Kyoto Animation: Megane-hen
  - A18153 # Kyoukai no Kanata
-
  - A1412 # Lupin III
  - A235 # Detective Conan
  - A6115 # Lupin III vs. Detective Conan
-
  - A1412 # Lupin III
  - A18429 # Lupin III vs. Detective Conan: The Movie
  - A235 # Detective Conan
-
  - A12769 # Yumemakura Baku Twilight Gekijou
  - A305 # Abashiri Ikka
  - A4923 # Akai Hayate
-
  - A2852 # Accelerando: Datenshi-tachi no Sasayaki
  - A6194 # Stretta The Animation
-
  - A188 # Gosenzo Sane
  - A6690 # Anata dake Konbanwa
-
  - A4561 # Zoku Gosenzo Sane
  - A6690 # Anata dake Konbanwa
-
  - A1887 # Lucky☆Star
  - A3080 # Anime Tenchou
  - A9875 # Anime Tenchou x Touhou Project
-
  - A9861 # Anime Tenchou Movie
  - A9875 # Anime Tenchou x Touhou Project
-
  - A13677 # Ao no Exorcist Movie Special
  - A9627 # Kakko Kawaii Sengen!
-
  - A10443 # Birei Okami Mie
  - A9312 # Mofukuzuma
-
  - A15125 # Teekyuu
  - A19297 # Ketsuekigata-kun! Featuring Yuri & Nasuno
-
  - A6875 # Iron Man
  - A6918 # Wolverine
  - A6920 # Blade
-
  - A10954 # Toei Robot Girls
  - A1845 # Gaiking: Legend of Daiku-Maryu
  - A1986 # Wakusei Robo Danguard Ace
  - A3932 # Magnerobo Ga-Keen
  - A6970 # Choujin Sentai Baratack
-
  - A289 # Comic Party
  - A472 # To Heart
-
  - A2722 # Crusher Joe
  - A424 # Dirty Pair
-
  - A355 # Shakugan no Shana
  - A486 # Kino no Tabi: The Beautiful World
  - A6628 # Dengeki Bunko 2007 Movie Festival Special
  - A940 # Inukami!
-
  - A10934 # Itsuka Tenma no Kuro Usagi OVA
  - A8086 # Densetsu no Yuusha no Densetsu
-
  - A2222 # Dr. Slump: Arale-chan
  - A223 # Dragon Ball
-
  - A12885 # Dynamic Super Robots Soushingekki
  - A938 # Shin Getter Robo tai Neo Getter Robo
-
  - A15335 # Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare
  - A19261 # Gintama x Mameshiba
  - A7261 # Mameshiba
-
  - A9863 # SKET Dance
  - A9969 # Gintama
-
  - A11859 # Queens Blade: Rebellion
  - A13161 # Hagure Yuusha no Aesthetica
  - A14663 # Queens Blade Rebellion vs. Hagure Yuusha no Aesthetica
-
  - A19279 # Pony Metal U-GAIM Promotion Film
  - A2044 # Mahou no Tenshi Creamy Mami
  - A2598 # Juusenki L-Gaim
-
  - A143 # Kannazuki no Miko
  - A1810 # Kyoushirou to Towa no Sora
-
  - A1037 # Saint Beast: Seijuu Kourin-hen
  - A682 # Otogi Story Tenshi no Shippo
-
  - A10033 # Toriko
  - A21 # One Piece
  - A813 # Dragon Ball Z
-
  - A177 # Tsubasa Chronicle
  - A861 # xxxHOLiC
-
  - A4918 # xxxHOLiC Shunmuki
  - A4938 # Tsubasa: Shunraiki
-
  - A10681 # Blood-C: The Last Dark
  - A793 # xxxHOLiC Movie: Manatsu no Yoru no Yume
-
  - A11597 # Nisemonogatari
  - A11981 # Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari
-
  - A28149 # Nihon Animator Mihonichi
  - A80 # Mobile Suit Gundam
-
  - A147 # Kimi ga Nozomu Eien
  - A80 # Mobile Suit Gundam
-
  - A29820 # Channel 5.5 4th Season
  - A338 # Versailles no Bara
-
  - A1698 # Nodame Cantabile
  - A29823 # Channel 5.5 3rd Season
-
  - A2076 # Kindaichi Shounen no Jikenbo (TV)
  - A29821 # Channel 5.5
-
  - A17187 # Ghost in the Shell: Arise - Border:1 Ghost Pain
  - A29822 # Channel 5.5 2nd Season
-
  - A21 # One Piece
  - A3545 # Kochira Katsushikaku Kameari Kouenmae Hashutsujo (TV)
  - A813 # Dragon Ball Z
  - A971 # Astro Boy: Tetsuwan Atom
-
  - A28351 # Hikari no Megami
  - A527 # Pokemon
-
  - A1816 # Sonic X
  - A28351 # Hikari no Megami
-
  - A2263 # Sonic★the★Hedgehog
  - A28351 # Hikari no Megami
-
  - A28351 # Hikari no Megami
  - A5265 # Mega Man
-
  - A1854 # Rockman Hoshi ni Negai wo
  - A28351 # Hikari no Megami
-
  - A18897 # Nisekoi
  - A5081 # Bakemonogatari
-
  - A2253 # Mazinger Z
  - A31517 # Ninja-tai Gatchaman ZIP!
-
  - A2253 # Mazinger Z
  - A31699 # Good Morning!!! Doronjo
-
  - A3008 # Time Bokan Series: Yatterman
  - A31699 # Good Morning!!! Doronjo
-
  - A30 # Neon Genesis Evangelion
  - A3444 # The Ultraman
  - A80 # Mobile Suit Gundam
-
  - A3444 # The Ultraman
  - A3785 # Evangelion: 3.0 You Can (Not) Redo
  - A80 # Mobile Suit Gundam
-
  - A27829 # Heavy Object
  - A6213 # Toaru Kagaku no Railgun
-
  - A27829 # Heavy Object
  - A4654 # Toaru Majutsu no Index
-
  - A13863 # Arve Rezzle: Kikaijikake no Yousei-tachi
  - A14347 # Ryo
  - A14349 # Little Witch Academia
  - A14353 # Death Billiards
-
  - A31165 # Meiji x Kokosake & anohana Receipt Oubo Campaign
  - A9989 # Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.
-
  - M29937 # Bara Manga Daioh
  - M371 # Ichigo Mashimaro
  - M85 # Azumanga Daioh
-
  - M16816 # Durarara!!
  - M21135 # Etsusa Oohashi Gaiden: 5656! Knights Strange Night
-
  - M11 # Naruto
  - M11926 # Jump Super Stars
  - M13 # One Piece
  - M1505 # Bobobo-bo Bo-bobo
  - M16038 # Toriyama Akira ○-saku Gekijou
  - M42 # Dragon Ball
  - M43 # Eyeshield 21
  - M45 # Ichigo 100%
  - M796 # Dr. Slump
-
  - M16124 # Maburaho VS Slayers!? - Dragon All Stars Gekitouhen
  - M20870 # Slayers VS Orphen
  - M8876 # Slayers
-
  - M10 # xxxHOLiC
  - M16010 # K-Dash
  - M32037 # Drug & Drop
  - M9 # Tsubasa: RESERVoir CHRoNiCLE
-
  - M10105 # Inumarudashi
  - M1414 # SKET Dance
  - M44 # Gintama
-
  - M24294 # Ao Haru Ride
  - M52389 # Ore Ride!!
-
  - M38105 # Kase-san Series
  - M55003 # Hirari, Bessatsu: Bukatsu Joshi Anthology - Houkago!
-
  - M1474 # Devilman
  - M8560 # Tetsu no Shojo Jun
-
  - M14155 # Continue
  - M24 # D.Gray-man
-
  - M31499 # Nisekoi
  - M36933 # Ore Monogatari!!
-
  - M31499 # Nisekoi
  - M35243 # Haikyuu!!
