:anime:
  - 35614
  - 99999999
:manga:
  - 59267
  - 21327 # Chimamire Tenshi
:ranobe:
  - 88888888
:character:
  - 110319 # Bin Kyoudai "Shippo Brothers"
  - 138658 # Carnap
  - 147901 # Aimi "Ami-chan" Tabata
  - 154599 # Urmd Avdol
  - 154600 # Captain Valentine
  - 25685 # Ben Naegino
  - 36063 # Hina
  - 59077 # Goda
  - 144825 # Sakurai Motoki
  - 72061 # Kanzaki Urashima
  - 72225 # Chouji
  - 72897 # Tanba Momochi
  - 72895 # Masago The Silk Spinner
  - 30508 # Kikyo Kogure
  - 30527 # Kayo Momochi
  - 30549 # Kagame
  - 72881 # Genzo The Harpist
  - 120989 # Granny
  - 70493 # Tokugawa
  - 121149 # Hicval
  - 112925 # Kiel
  - 121125 # L'Arc Berg
  - 123907 # Mald
  - 73283 # Shouta Aikawa
:person:
  - 32789
  - 40128
