:anime:
  - 111111111 # for test purposes
  - 35614
:manga:
  - 222222222 # for test purposes
  - 59267
  - 21327 # Chimamire Tenshi
:ranobe:
  - 333333333 # for test purposes
:character:
  - 444444444 # for test purposes
:person:
  - 555555555 # for test purposes
  - 32789
  - 40128
