:bad_names:
 - \d+
 - первыйсезон
 - второйсезон
 - третийсезон
 - сезонпервый
 - сезонвторой
 - сезонтретий
 - спецвыпуск\d+
 - firstseason
 - secondseason
 - thirdseason
 - anime
 - theanime
 - themovie
 - movie

:letter_synonyms:
  and: '&'
  ß: ss
  ×: x
  tv: тв
  ova: ова
  ona: она
  movie: фильм
  u: h

:word_synonyms:
  kanojo: heroine
  magika: magica
  special: specials
  wo: o
  i: '1'
  ii: '2'
  iii: '3'
  iv: '4'
  v: '5'
  vi: '6'
  tv1: 1st season
  tv2: 2nd season
  tv3: 3rd season
  tv4: 4th season
  tv5: 5th season
  tv6: 6th season
  tv1: 1st season
  tv2: 2nd season
  tv3: 3rd season
  tv4: 4th season
  tv5: 5th season
  tv6: 6th season
  s1: 1st season
  s2: 2nd season
  s3: 3rd season
  s4: 4th season
  s5: 5th season
  s6: 6th season

:regexp_replaces:
  '\b(тв|tv|ova|tb)\s*-?\s*\d$': ''
  '\btv$': ''
  '\b\d{4}$': ''
  '\bseason (\d+)\b': ' s\1'
  '\bs(\d+)\b': ' season \1'
  '(?<= )([456789])$': '\1th season'
  '(?<= )2$': '2nd season'
  '(?<= )3$': '3rd season'
  '^the ': ''
  '\bi\b': ''
  '!': ''
  ' plus$': '+'
  ' the animation$': ''
  ' series \d$': ''
  '(?<!u)u(?!u)': 'uu'
  's(?!h)': 'sh'
  '(?<=[wrtpsdfghjklzxcvbnmy])o(?!u)': 'ou'
