---
- :neko_id: :animelist
  :level: 1
  :image: http://i.imgur.com/v7x2w7p.png
  :border: "#E52B50"
  :title_ru: Добро пожаловать!
  :text_ru: Даже путь в тысячу ли начинается с первого шага.
- :neko_id: :animelist
  :level: 2
  :image: https://kawai.shikimori.org/system/user_images/original/50587/459471.jpg
  :border: "#ff0000"
  :title_ru: Это всего лишь начало.
  :text_ru: Вы достигли магического трехзначного числа. Но не время останавливаться,
    все еще впереди!
- :neko_id: :animelist
  :level: 3
  :image: https://shikimori.org/assets/achievements/anime/list_2-0d3f017394ff1743a05c4971ef759a3fe3c17c6520c3e0cb7a7d8e2eea23f576.jpg
  :border: "#6A5ACD"
  :title_ru: Мои силы растут!
  :text_ru: 
- :neko_id: :animelist
  :level: 4
  :image: 
  :border: 
  :title_ru: 
  :text_ru: 
- :neko_id: :animelist
  :level: 5
  :image: 
  :border: 
  :title_ru: 
  :text_ru: 
- :neko_id: :animelist
  :level: 6
  :image: 
  :border: 
  :title_ru: Знаток
  :text_ru: 
- :neko_id: :animelist
  :level: 7
  :image: http://i.imgur.com/8dY1YdU.jpg
  :border: "#071746"
  :title_ru: Сатанинский предел?
  :text_ru: Вами движет поистине дьявольское упорство.
- :neko_id: :animelist
  :level: 8
  :image: 
  :border: 
  :title_ru: This is not even my final form!
  :text_ru: 
- :neko_id: :animelist
  :level: 9
  :image: 
  :border: 
  :title_ru: Коллекционер
  :text_ru: Аниме много не бывает.
- :neko_id: :animelist
  :level: 10
  :image: 
  :border: 
  :title_ru: Маньяк
  :text_ru: Может все же стоит взять передышку и заняться чем-нибудь другим?
- :neko_id: :animelist
  :level: 11
  :image: 
  :border: 
  :title_ru: Легенда
  :text_ru: 
- :neko_id: :animelist
  :level: 12
  :image: 
  :border: 
  :title_ru: Ками-сама
  :text_ru: 
- :neko_id: :animelist
  :level: 13
  :image: 
  :border: 
  :title_ru: Недосягаемый
  :text_ru: Такое не под силу живому человеку. Вы уверены в том, что посмотрели все
    это?
- :neko_id: :comedy
  :level: 1
  :image: https://kawai.shikimori.org/system/user_images/original/50587/458876.jpg
  :border: "#5dbdd9"
  :title_ru: But then i lol'd
  :text_ru: Неужели вам понравился японский юмор?
- :neko_id: :otaku
  :level: 1
  :image: http://i.yapx.ru/JEvZ.jpg
  :border: "#FF496C"
  :title_ru: Эскапизм
  :text_ru: Иллюзии захватывают ваш разум.
- :neko_id: :otaku
  :level: 2
  :image: https://shikimori.org/assets/achievements/anime/otaku_4-381b895909dc0141f22bd836188fc43bd64f06f655c3c708d41a2ce56018fc13.jpg
  :border: "#474A51"
  :title_ru: Фетишизм
  :text_ru: Как рыба в воде.
- :neko_id: :otaku
  :level: 3
  :image: https://yapcdn.net/se3/1/tSDzHDAI3i0.jpg
  :border: "#2F4F4F"
  :title_ru: NEET
  :text_ru: Увлечение эротическим контентом начинает сказываться на вашей реальной
    жизни.
- :neko_id: :otaku
  :level: 4
  :image: https://i.yapx.ru/JMeO.gif
  :border: "#CD9575"
  :title_ru: Хикикомори
  :text_ru: Уровень вашего либидо достиг максимального. Окружающие трепещут.
