- 39363 # Astro Boy: Tetsuwan Atom - 10-man Kounen no Raihousha - IGZA - Показ в кинотеатрах 
- 39362 # Astro Boy: Tetsuwan Atom - Getsumen Kichi - Kieta Robot no Nazo - Эксклюзивный показ в планетарии
- 3570 # Yadosagashi - Эксклюзив Гибли
- 35267 # Shingeki no Kyojin-ten 360° Taikan Theater -  VR ,доступен 1 эп
- 39478 # Shingeki no Kyojin in the Dome: Heishi-tachi no Hoshizora - Показ в планетарии
- 19401 # Kuusou no Sora Tobu Kikaitachi - Эксклюзив Гибли
- 10118 # Ginga Tetsudou 999: Jikuu wo Koeta Energy no Tabi -  Эксклюзивный заказ для электро-компании. Сайт давно закрыт. В свободном доступе не существует
- 30481 # Ginga Tetsudou 999 for Planetarium - Показ в планетарии
- 7285 # Ginga Tetsudou 999: Diamond Ring no Kanata e - Показ в кинотеатре
- 30483 # Ginga Tetsudou 999: Akai Hoshi Betelgeuze - Inochi no Kagayaki - Показ в планетарии
- 12163 # Ginga Tetsudou 999: Hoshizora wa Time Machine - Нет в свободном доступе
- 32133 # Kemushi no Boro - Эксклюзив Гибли
- 6463 # Hoshi wo Katta Hi - Эксклюзив Гибли
- 36760 # Detective Conan: The Magician of Starlight - Разовый показ на выставке в Яп
- 33146 # Detective Conan: Let's Try a Curious Experiment! - Нет в свободном доступе
- 9785 # Detective Conan: Conan vs. Kid - Shark & Jewel - 3D IMAX фильм, показанный только в Музее Suntory в Осаке
- 9786 # Detective Conan: Conan vs. Kid - Jet Black Sniper - 3D IMAX фильм, показанный только в Музее Suntory в Осаке
- 33151 # Meitantei Conan: Kodai Kyouryuu no Nazo ni Semare! - Нет в свободном доступе
- 36269 # Detective Conan: Anti-Crime Guide - Образовательное аниме .Нет в свободном доступе
- 501 # Doraemon - утерянный сериал
- 2630 # Doraemon Meets Hattori the Ninja - Нет в свободном доступе
- 23675 # Hi no Tori: Kizuna-hen - Короткий фильм показан в трех местах Яп
- 7651 # Ningen Shikkaku: Director's Cut-ban - Показ в кинотеатре. Утеряно. Нет в свободном доступе
- 39361 # Tetsuwan Atom to Sagurou! Dosei wo Mawaru Shinpi no Hoshi Titan - Фильм для планетария
- 33511 # Koro-sensei Q! - Не существует
- 23943 # Mobile Suit Gundam Unicorn: One of Seventy Two - Показ только в Gundam Front Tokyo
- 8839 # Gundam Neo Experience 0087: Green Divers - myanimelist.net/forum/?topicid=1359468
- 22893 # Mon Cheri CoCo - Утерянный сериал
- 8632 # Chuuzumou - Эксклюзив Гибли
- 8442 # Maze☆Bakunetsu Jikuu: Tenpen Kyoui no Giant - Утерянный фильм
- 3603 # JoJo no Kimyou na Bouken: Phantom Blood - Сохранились только отрывки
- 10354 # Kakomareta Sekai - Был доступен на сайте Синкая во времена царя гороха. На данный момент недоступен и неизвестно существует ли
- 2895 # Kujiratori - Эксклюзив Гибли
- 9875 # Anime Tenchou x Touhou Project - ???
- 20007 # Hi Gekiga Ukiyoe Senya Ichiya - Нет в свободном доступе. Утеряно?
- 35070 # 3-Nen D-Gumi Glass no Kamen: Tobidase! Watashitachi no Victory Road - Можно было увидеть только в VR-театр в Японии
- 19165 # Fate/Zero Cafe -  myanimelist.net/forum/?topicid=1765882 Посмотреть не представляется возможным
- 36054 # Teekyuu 9 Specials - Не существуют
- 11787 # Toriko: Barbarian Ivy wo Hokaku Seyo! - Разовый показ на Джамп-фесте
- 12763 # 0-sen Hayato - Утерянный сериал
- 31669 # Takamiya Nasuno Desu!: Teekyuu Spin-off Specials - Не существуют
- 23651 # Hanawa Hekonai Kappa Matsuri - Древние аниме, которые утеряны навсегда
- 17387 # Imokawa Mukuzo: Genkanban no Maki - Древние аниме, которые утеряны навсегда
- 23187 # Chamebou Shin Gachou: Nomi Fuufu Shikaeshi no Maki - Древние аниме, которые утеряны навсегда
- 24577 # Imokawa Mukuzo: Chuugaeri no Maki - Древние аниме, которые утеряны навсегда
- 24575 # Yume no Jidousha - Древние аниме, которые утеряны навсегда
- 24573 # Neko to Nezumi - Древние аниме, которые утеряны навсегда
- 23183 # Itazura Post - Древние аниме, которые утеряны навсегда
- 23185 # Chamebou Kuukijuu no Maki - Древние аниме, которые утеряны навсегда
- 23191 # Chokin no Susume - Древние аниме, которые утеряны навсегда
- 23181 # Otogi Banashi: Bunbuku Chagama - Древние аниме, которые утеряны навсегда
- 10756 # Shita-kiri Suzume - Древние аниме, которые утеряны навсегда
- 30957 # Yukidaruma - Древние аниме, которые утеряны навсегда
- 10759 # Kintarou - Древние аниме, которые утеряны навсегда
- 10760 # Issunboushi - Древние аниме, которые утеряны навсегда
- 21761 # Ari to Hato - Древние аниме, которые утеряны навсегда
- 28689 # Noroma na Jiji - Древние аниме, которые утеряны навсегда
- 24857 # Akagaki Genzou: Tokuri no Wakare - Древние аниме, которые утеряны навсегда
- 22995 # Shisei Sasshin - Древние аниме, которые утеряны навсегда
- 7495 # Nonki na Tou-san Ryuuguu Mairi - Древние аниме, которые утеряны навсегда
- 24881 # Bunbuku Chagama - Древние аниме, которые утеряны навсегда
- 35493 # Chuukichi wa Kaetta - Древние аниме, которые утеряны навсегда
- 35491 # Kaeru wa Kaeru - Древние аниме, которые утеряны навсегда
- 35490 # Tanukichi no Ohanashi - Древние аниме, которые утеряны навсегда
- 7354 # Chikara to Onna no Yo no Naka - Древние аниме, которые утеряны навсегда
- 35212 # Adauchi Karasu - Древние аниме, которые утеряны навсегда
- 24981 # Yowamushi Chinsengumi - Древние аниме, которые утеряны навсегда
- 7500 # Maabou no Shounen Koukuu Tsuwamono - Древние аниме, которые утеряны навсегда
- 31948 # Sora no Arawashi - Древние аниме, которые утеряны навсегда
- 23969 # Fuku-chan no Kishuu - Древние аниме, которые утеряны навсегда
- 27575 # Spy Gekimetsu - Древние аниме, которые утеряны навсегда
- 23971 # Fuku-chan no Zousan Butai - Древние аниме, которые утеряны навсегда
- 33132 # Shin Kachikachi Yama - Древние аниме, которые утеряны навсегда
- 15393 # Sakura no Ondo - Оригинальный анимационный фильм от ufotable. Показывали только в кинотеатре студии и на фестивале короткометражных фильмов Саппоро. Нет в свободном доступе
- 22419 # Acchi Kocchi - Утеряно. Не существует
- 34167 # Cocolors - Показ только в кинотеатрах Яп
- 6975 # Koro no Dai Sanpo - Эксклюзив Гибли
- 25441 # Shin Strange+ Special - Нет в свободном доступе
- 18729 # Marginal Prince: Gekkeiju no Ouji-tachi - Tokyo Merry-Go-Round - Нет в свободном доступе
- 32158 # Mobile Suit Gundam-san (Movie) - (Эпизод был показан на настенном дисплее G на стенах комплекса Diver City Tokyo в Одайбе, Токио в 18: 00, 19: 00, 20: 00 и 21: 00)
